# Generated by Django 2.0 on 2021-05-03 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20)),
                ('dpwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('epwd', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=20)),
                ('d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.dept')),
            ],
        ),
        migrations.CreateModel(
            name='qj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('statime', models.DateField()),
                ('endtime', models.DateField()),
                ('time', models.DateField(auto_now_add=True)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.emp')),
            ],
        ),
        migrations.CreateModel(
            name='shenpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stime', models.CharField(max_length=20, null=True)),
                ('sys', models.CharField(max_length=20)),
                ('yes_ok', models.CharField(max_length=20, null=True)),
                ('say', models.CharField(max_length=50, null=True)),
                ('qid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.qj')),
            ],
        ),
        migrations.CreateModel(
            name='yuanyin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='qj',
            name='yid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.yuanyin'),
        ),
    ]
