
# Generated by Django 2.0 on 2021-05-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='d',
            new_name='did',
        ),
    ]
